import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "ruleta",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="m-auto grid min-h-screen w-full grid-rows-[auto,1fr,auto] bg-slate-950 px-16 font-sans antialiased ">
        <header className="mb-8 text-xl font-bold leading-[4rem]">
          <Link href="/">Coliwheel</Link>
        </header>
        <main>{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} ruleta
        </footer>
      </body>
    </html>
  );
}
