import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

export const metadata: Metadata = {
  title: "ruleta",
  description: "Generated by colidevs CLI",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto]  bg-gradient-to-br from-indigo-900 to-purple-700 p-8 px-4 font-sans antialiased">
        <header className="rounded-lg bg-indigo-950 text-center text-xl font-bold leading-[4rem] ">
          <Link href="/">Coliwheel</Link>
        </header>
        <main>{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} ruleta
        </footer>
      </body>
    </html>
  );
}
